#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Thu Apr 24 11:30:13 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ChangePasswordDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ChangePasswordDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.change_pw_label = wx.StaticText(self, wx.ID_ANY, _("Change Password"))
        self.op_label = wx.StaticText(self, wx.ID_ANY, _("Old Password:"))
        self.oldPassword = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.np_label = wx.StaticText(self, wx.ID_ANY, _("New Password:"))
        self.newPassword = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.np2_label = wx.StaticText(self, wx.ID_ANY, _("Verify New Password:"))
        self.verifyPassword = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.changePasswordMsg = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_READONLY | wx.TE_CENTRE | wx.NO_BORDER)
        self.changeButton = wx.Button(self, wx.ID_OK, "")
        self.cancelButton = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnChangePassword, self.changeButton)
        self.Bind(wx.EVT_BUTTON, self.OnCancel, self.cancelButton)
        # end wxGlade
        self.Bind(wx.EVT_CLOSE, self.OnCancel)

    def __set_properties(self):
        # begin wxGlade: ChangePasswordDialog.__set_properties
        self.SetTitle(_("Change Password"))
        self.change_pw_label.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.op_label.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.oldPassword.SetMinSize((150, 27))
        self.oldPassword.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.np_label.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.newPassword.SetMinSize((150, 27))
        self.newPassword.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.np2_label.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.verifyPassword.SetMinSize((150, 27))
        self.verifyPassword.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.changePasswordMsg.SetBackgroundColour(wx.Colour(240, 240, 240))
        self.changePasswordMsg.SetForegroundColour(wx.Colour(255, 0, 0))
        self.changePasswordMsg.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.changeButton.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.cancelButton.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ChangePasswordDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 4, 10, 10)
        sizer_1.Add((20, 30), 0, 0, 0)
        sizer_1.Add(self.change_pw_label, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add((20, 30), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.op_label, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.oldPassword, 0, wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.np_label, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.newPassword, 0, wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        grid_sizer_1.Add(self.np2_label, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.verifyPassword, 0, wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_1.Add((20, 10), 0, 0, 0)
        sizer_1.Add(self.changePasswordMsg, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add((20, 10), 0, 0, 0)
        sizer_2.Add(self.changeButton, 0, 0, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_2.Add(self.cancelButton, 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnChangePassword(self, event):  # wxGlade: ChangePasswordDialog.<event_handler>
        """
        Button handler for changing the password
        """
        oldpw = self.oldPassword.GetValue()
        pw = self.newPassword.GetValue()
        pw2 = self.verifyPassword.GetValue()
        if pw != pw2:
            self.changePasswordMsg.SetValue("Verify password does not match new password")
            return
        (rc,msg) = self.db.ChangePassword(oldpw,pw)
        if rc != 0:
            print "Error in ChangePassword, rc = %d" % rc
            print msg
            self.changePasswordMsg.SetValue(str(msg))
        else:
            self.EndModal(1)

    def OnCancel(self, event):  # wxGlade: ChangePasswordDialog.<event_handler>
        """
        Button handler for closing the dialog
        """
        self.EndModal(0)
        
    def SetDb(self,db):
        """
        Sets the database object.
        """
        self.db = db

# end of class ChangePasswordDialog
class ChangePW(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        change_password_dialog = ChangePasswordDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(change_password_dialog)
        change_password_dialog.Show()
        return 1

# end of class ChangePW

if __name__ == "__main__":
    gettext.install("changePW") # replace with the appropriate catalog name

    changePW = ChangePW(0)
    changePW.MainLoop()