#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Wed Jun 25 20:07:19 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class TouchFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TouchFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.rgb_video_touch_panel = wx.Panel(self, 223)
        self.thermal_video_touch_panel = wx.Panel(self, 223)
        self.touchscreen_msg = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.multi_video_touch_panel = wx.Panel(self, 223)
        self.touch_record_button = wx.Button(self, wx.ID_ANY, _("Record"))
        self.touch_snapshot_button = wx.Button(self, wx.ID_ANY, _("Take\nMulti-Spectral\nSnapshot"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnTouchRecord, self.touch_record_button)
        self.Bind(wx.EVT_BUTTON, self.OnTouchSnapshot, self.touch_snapshot_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: TouchFrame.__set_properties
        self.SetTitle(_("VA-PUPC Touchscreen Input"))
        self.SetSize((800, 480))
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.rgb_video_touch_panel.SetMinSize((640, 360))
        self.thermal_video_touch_panel.SetMinSize((160, 120))
        self.touchscreen_msg.SetMinSize((440, 120))
        self.touchscreen_msg.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.multi_video_touch_panel.SetMinSize((160, 160))
        self.touch_record_button.SetMinSize((160, 80))
        self.touch_record_button.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.touch_snapshot_button.SetMinSize((160, 80))
        self.touch_snapshot_button.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TouchFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.rgb_video_touch_panel, 0, wx.EXPAND, 0)
        sizer_4.Add(self.thermal_video_touch_panel, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 120), 0, 0, 0)
        sizer_4.Add(self.touchscreen_msg, 0, wx.EXPAND, 0)
        sizer_4.Add((20, 120), 0, 0, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        sizer_3.Add(self.multi_video_touch_panel, 0, wx.EXPAND, 0)
        sizer_3.Add((20, 40), 0, wx.EXPAND, 0)
        sizer_3.Add(self.touch_record_button, 0, wx.EXPAND, 0)
        sizer_3.Add((20, 40), 0, wx.EXPAND, 0)
        sizer_3.Add(self.touch_snapshot_button, 0, wx.EXPAND, 0)
        sizer_3.Add((20, 80), 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnTouchRecord(self, event):  # wxGlade: TouchFrame.<event_handler>
        """
        Event handler for Record button
        """
        self.GetParent().OnRecordClick(event)

    def OnTouchSnapshot(self, event):  # wxGlade: TouchFrame.<event_handler>
        """
        Event handler for Take Multi-Spectral Snapshot button
        """
        self.GetParent().OnMSSnapshotClick(event)
        
    def SetMsg(self,msg):
        """
        Sets the message field on the touchscreen and updates the screen
        """
        self.touchscreen_msg.SetValue(msg)
        self.Update()

# end of class TouchFrame
if __name__ == "__main__":
    gettext.install("touchscreen") # replace with the appropriate catalog name

    touchscreen = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    touch_frame = TouchFrame(None, wx.ID_ANY, "")
    touchscreen.SetTopWindow(touch_frame)
    touch_frame.Show()
    touchscreen.MainLoop()